services:
  lms.api:
    image: ${DOCKER_REGISTRY-}lmsapi
    build:
      context: .
      dockerfile: Lms.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=LmsDb;User=sa;Password=insightful3d!;TrustServerCertificate=True"
    depends_on:
        - mssql
    ports:
     - "8080:8080"
     - "8081:8081"
 
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
        SA_PASSWORD: "insightful3d!"
        ACCEPT_EULA: "Y"
    ports:
       - "1433:1433" 
    volumes:
       - mssql_data:/var/opt/mssql

volumes:
    mssql_data:    